In [1]:
import torch

In [2]:
x = torch.tensor([1],device=0)
x

tensor([1], device='cuda:0')

In [3]:
x.to(1)

tensor([1], device='cuda:1')

In [4]:
x.to('cpu')

tensor([1])

In [5]:
x.to(1)

tensor([1], device='cuda:1')

In [6]:
x = torch.tensor([1.0,2.0],device=0)
x

tensor([1., 2.], device='cuda:0')

In [7]:
x.to(1)

tensor([1., 2.], device='cuda:1')

In [10]:
x.to('cpu')

tensor([1., 2.])